export const FETCH_LIST_CAMPAIGNS = 'FETCH_LIST_CAMPAIGNS';
export const SET_LIST_CAMPAIGNS = 'SET_LIST_CAMPAIGNS';

export const CREATE_CAMPAIGN = 'CREATE_CAMPAIGN';
export const UPDATE_CAMPAIGN = 'UPDATE_CAMPAIGN';
export const DELETE_CAMPAIGN = 'DELETE_CAMPAIGN';

export const FETCH_LIST_LOGIC_PATTERN = 'FETCH_LIST_LOGIC_PATTERN';
export const FETCH_LIST_BET_PATTERN = 'FETCH_LIST_BET_PATTERN';

export const SET_LIST_LOGIC_PATTERN = 'SET_LIST_LOGIC_PATTERN';
export const SET_LIST_BET_PATTERN = 'SET_LIST_BET_PATTERN';
